/**
 * Created by hasee on 2017/9/23.
 */

export const REQUEST_ARTICLES = 'REQUEST_ARTICLES'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE'
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES'
export const REQUEST_HOT_ARTICLES = 'REQUEST_HOT_ARTICLES'
export const GET_HOT_ARTICLES_SUCCESS = 'GET_HOT_ARTICLES_SUCCESS'
export const GET_HOT_ARTICLES_FAILURE = 'GET_HOT_ARTICLES_FAILURE'
export const ADD_ARTICLES_SUCCESS = 'ADD_ARTICLES_SUCCESS'
export const REQUEST_ARTICLE_DETAIL = 'REQUEST_ARTICLE_DETAIL'
export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS'
export const GET_ARTICLE_DETAIL_FAILURE = 'GET_ARTICLE_DETAIL_FAILURE'

export const REQUEST_ARCHIVES = 'REQUEST_ARCHIVES'
export const GET_ARCHIVES_FAILURE = 'GET_ARCHIVES_FAILURE'
export const GET_ARCHIVES_SUCCESS = 'GET_ARCHIVES_SUCCESS'

export const REQUEST_AUTH = 'REQUEST_AUTH'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_LOGOUT = 'USER_LOGOUT'

export const REQUEST_GITHUB_DATA = 'REQUEST_GITHUB_DATA'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
export const GET_REPOSITORIES_SUCCESS = 'GET_REPOSITORIES_SUCCESS'
export const GET_REPOSITORIES_FAILURE = 'GET_REPOSITORIES_FAILURE'

export const REQUEST_HITOKOTO = 'REQUEST_HITOKOTO'
export const REQUEST_HITOKOTO_SUCCESS = 'REQUEST_HITOKOTO_SUCCESS'
export const REQUEST_HITOKOTO_FAILURE = 'REQUEST_HITOKOTO_FAILURE'

export const SET_USER_AGENT = 'SET_USER_AGENT'
export const SET_MOBILE_LAYOUT = 'SET_MOBILE_LAYOUT'
export const SET_NUM_PER_PAGE = 'SET_NUM_PER_PAGE'

export const REQUEST_TAGS = 'REQUEST_TAGS'
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE'
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'
