/**
 * Created by hasee on 2017/9/23.
 */

export const GET_ARTICLES = 'GET_ARTICLES'
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES'
export const GET_HOT_ARTICLES = 'GET_HOT_ARTICLES'
export const ADD_ARTICLES = 'ADD_ARTICLES'
export const GET_ARTICLE_DETAIL = 'REQUEST_ARTICLE_DETAIL'

export const GET_ARCHIVES = 'GET_ARCHIVES'

export const REQUEST_AUTH = 'REQUEST_AUTH'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_USER = 'GET_USER'
export const GET_REPOSITORIES = 'GET_REPOSITORIES'

export const GET_HITOKOTO = 'GET_HITOKOTO'

export const SET_USER_AGENT = 'SET_USER_AGENT'
export const SET_MOBILE_LAYOUT = 'SET_MOBILE_LAYOUT'
export const SET_NUM_PER_PAGE = 'SET_NUM_PER_PAGE'

export const GET_TAGS = 'GET_TAGS'
